### ISSUE TITLE
Bug: Clan Pestilence victory conditions not registering 

### ISSUE THREAD

**Issue by StevenSwitten** [msolefonte/tww2-vco2-main#5]
Hi, I reported this bug on Steam, but I thought I could give you some extra information on here.
This is what the victory condition screen looks like: 
![20200802215834_1](https://user-images.githubusercontent.com/30682786/89131274-b9654600-d50b-11ea-8f23-9d42610643d1.jpg)

The actual number of Plague Abbeys I own is 6
I also have 1 Grand Plague Couldron, that condition used to be ticked, but isn't anymore upon reloading the savegame.
The first 2 conditions do seem to successfully register.

The long victory view is similar:
![20200802215843_1](https://user-images.githubusercontent.com/30682786/89131307-0fd28480-d50c-11ea-9e66-2dc27efda8cd.jpg)

List of active mods:
mod "better_camera_mod.pack";
mod "mod_configuration_tool.pack";
mod "community_bugfix_mod.pack";
mod "faster_end_turn_camera.pack";
mod "jadawin_diplo_rebalance.pack";
mod "llr_wec.pack";
mod "marthdiploskip.pack";
mod "scipion's_recruit_legendary_lords.pack";
mod "sensei_ngpp.pack";
mod "sm0_save_cam_settings.pack";
mod "uimf.pack";
mod "watchful_sentries.pack";
mod "wec_one_button_respec.pack";
mod "@nojoinwar.pack";
mod "skill_queue.pack";
mod "austins_yawg.pack";
mod "Jaffa_tower_range.pack";
mod "zzz_vco2_framework.pack";
mod "vco2_main.pack";

I tried deactivating all mods except yours, but the victory screen looks the same, and ending the turn crashes my game.
Before this campaign, I successfully ended a Barrow Legion campaign (on short victory) with this mod and the exact same modlist. If there's anything else I can provide to help, let me know.

Savegame file:
[Clan Pestilens_Auto-save1359343679.zip](https://github.com/msolefonte/tww2-vco2-main/files/5012815/Clan.Pestilens_Auto-save1359343679.zip)

**Comment by msolefonte** [comment]
Hi @StevenSwitten,

I forgot to answer here, but it was fixed time ago. Thanks for reporting!
